import { z } from "zod";
import { defineResource } from "./shared/resource.factory.js";

const common = { status: z.string().trim().optional() };
const definitions = {
  branches: {
    name: "Branch",
    delegate: "branch",
    required: ["name", "code", "username", "password"],
    searchable: ["name", "code", "username"],
    fields: {
      name: z.string().trim().min(1),
      code: z.string().trim().min(1),
      username: z.string().trim().min(3),
      password: z.string().min(6),
      phone: z.string().trim().nullable().optional(),
      email: z.string().email().nullable().optional(),
      address: z.string().trim().nullable().optional(),
      status: z.enum(["ACTIVE", "INACTIVE"]).optional(),
    },
  },
  staff: {
    name: "Staff",
    delegate: "staff",
    required: ["name", "phone"],
    searchable: ["name", "phone", "email"],
    fields: {
      name: z.string().trim().min(1),
      phone: z.string().trim().min(5),
      email: z.string().email().nullable().optional(),
      designation: z.string().trim().nullable().optional(),
      status: z.enum(["ACTIVE", "INACTIVE"]).optional(),
      joiningDate: z.coerce.date().nullable().optional(),
    },
  },
  customers: {
    name: "Customer",
    delegate: "customer",
    required: ["name", "phone"],
    searchable: ["name", "phone", "email"],
    requiredRelations: { staffId: "staff" },
    fields: {
      name: z.string().trim().min(1),
      phone: z.string().trim().min(5),
      email: z.string().email().nullable().optional(),
      dob: z.coerce.date().nullable().optional(),
      gender: z.string().trim().nullable().optional(),
      address: z.string().trim().nullable().optional(),
      notes: z.string().trim().nullable().optional(),
      status: z.enum(["ACTIVE", "INACTIVE"]).optional(),
      staffId: z.string().uuid().nullable().optional(),
    },
  },
  leads: {
    name: "Lead",
    delegate: "lead",
    required: ["name", "phone"],
    searchable: ["name", "phone", "interest"],
    requiredRelations: { staffId: "staff" },
    fields: {
      name: z.string().trim().min(1),
      phone: z.string().trim().min(5),
      email: z.string().email().nullable().optional(),
      source: z.string().trim().nullable().optional(),
      interest: z.string().trim().nullable().optional(),
      status: z
        .enum(["NEW", "CONTACTED", "QUALIFIED", "CONVERTED", "LOST"])
        .optional(),
      nextFollowUpAt: z.coerce.date().nullable().optional(),
      notes: z.string().trim().nullable().optional(),
      staffId: z.string().uuid().nullable().optional(),
    },
  },
  policies: {
    name: "Policy",
    delegate: "policy",
    required: [
      "customerId",
      "policyNumber",
      "insurer",
      "product",
      "policyType",
      "premium",
      "startDate",
      "expiryDate",
    ],
    searchable: ["policyNumber", "insurer", "product"],
    requiredRelations: { customerId: "customer" },
    fields: {
      customerId: z.string().uuid(),
      policyNumber: z.string().trim().min(1),
      insurer: z.string().trim().min(1),
      product: z.string().trim().min(1),
      policyType: z.string().trim().min(1),
      premium: z.coerce.number().nonnegative(),
      startDate: z.coerce.date(),
      expiryDate: z.coerce.date(),
      status: z.enum(["ACTIVE", "EXPIRED", "CANCELLED"]).optional(),
    },
  },
  renewals: {
    name: "Renewal",
    delegate: "renewal",
    required: ["policyId", "dueDate"],
    searchable: [],
    requiredRelations: { policyId: "policy" },
    fields: {
      policyId: z.string().uuid(),
      dueDate: z.coerce.date(),
      status: z
        .enum([
          "UPCOMING",
          "DUE_SOON",
          "DUE_TODAY",
          "EXPIRED",
          "RENEWED",
          "NOT_RENEWED",
        ])
        .optional(),
      reminderStage: z.string().trim().nullable().optional(),
      renewedAt: z.coerce.date().nullable().optional(),
      notes: z.string().trim().nullable().optional(),
    },
  },
  claims: {
    name: "Claim",
    delegate: "claim",
    required: ["customerId", "claimDate"],
    searchable: ["claimNumber"],
    requiredRelations: { customerId: "customer", policyId: "policy" },
    fields: {
      customerId: z.string().uuid(),
      policyId: z.string().uuid().nullable().optional(),
      claimNumber: z.string().trim().nullable().optional(),
      claimDate: z.coerce.date(),
      status: z
        .enum(["REPORTED", "UNDER_REVIEW", "APPROVED", "REJECTED", "SETTLED"])
        .optional(),
      amount: z.coerce.number().nonnegative().nullable().optional(),
      notes: z.string().trim().nullable().optional(),
    },
  },
  "follow-ups": {
    name: "Follow-up",
    delegate: "followUp",
    required: ["title", "dueAt"],
    searchable: ["title"],
    requiredRelations: {
      customerId: "customer",
      leadId: "lead",
      staffId: "staff",
    },
    fields: {
      customerId: z.string().uuid().nullable().optional(),
      leadId: z.string().uuid().nullable().optional(),
      staffId: z.string().uuid().nullable().optional(),
      title: z.string().trim().min(1),
      dueAt: z.coerce.date(),
      status: z.enum(["PENDING", "COMPLETED", "CANCELLED"]).optional(),
      notes: z.string().trim().nullable().optional(),
      completedAt: z.coerce.date().nullable().optional(),
    },
  },
  documents: {
    name: "Document",
    delegate: "document",
    required: ["type", "fileName", "fileUrl"],
    searchable: ["fileName", "type"],
    requiredRelations: {
      customerId: "customer",
      policyId: "policy",
      claimId: "claim",
    },
    fields: {
      customerId: z.string().uuid().nullable().optional(),
      policyId: z.string().uuid().nullable().optional(),
      claimId: z.string().uuid().nullable().optional(),
      type: z.string().trim().min(1),
      fileName: z.string().trim().min(1),
      fileUrl: z.string().trim().min(1),
    },
  },
  activities: {
    name: "Activity",
    delegate: "activity",
    required: ["type", "title"],
    searchable: ["title", "type"],
    requiredRelations: { customerId: "customer", staffId: "staff" },
    fields: {
      customerId: z.string().uuid().nullable().optional(),
      staffId: z.string().uuid().nullable().optional(),
      type: z.string().trim().min(1),
      title: z.string().trim().min(1),
      description: z.string().trim().nullable().optional(),
      metadata: z.record(z.unknown()).nullable().optional(),
    },
  },
  commissions: {
    name: "Commission",
    delegate: "commission",
    required: ["amount"],
    searchable: [],
    requiredRelations: { policyId: "policy", customerId: "customer" },
    fields: {
      policyId: z.string().uuid().nullable().optional(),
      customerId: z.string().uuid().nullable().optional(),
      amount: z.coerce.number().nonnegative(),
      status: z.enum(["PENDING", "PAID", "CANCELLED"]).optional(),
      earnedAt: z.coerce.date().optional(),
      paidAt: z.coerce.date().nullable().optional(),
    },
  },
};

export const resources = Object.fromEntries(
  Object.entries(definitions).map(([key, config]) => [
    key,
    defineResource(config),
  ]),
);
