/**
 * Seed data for categories and tags
 */

export const trendingTags = [
  "Digital Marketing",
  "Sustainable Living",
  "Mental Health & Wellness",
  "Personal Finance & Investing",
  "Cryptocurrency & Web3",
  "Remote Work & Freelancing",
  "Self-Care & Wellness",
  "Content Creation",
  "AI & Technology Trends",
  "Minimalism & Organization",
  "Productivity Hacks",
  "Online Business & E-commerce",
  "Personal Branding",
  "Fitness & Gym Tips",
  "Healthy Eating & Nutrition",
  "Travel on a Budget",
  "Home Automation",
  "Skilling & Career Growth",
  "Fashion & Sustainable Fashion",
  "Social Media Strategy",
  "Relationship Advice",
  "Productivity & Time Management",
  "Meditation & Mental Wellness",
  "Side Hustles & Passive Income",
  "Gaming & Esports",
  "Photography & Content Creation",
  "Interior Design & Home Decor",
  "Personal Development",
  "Entrepreneurship & Startups",
  "Lifestyle & Wellness Trends",
];

export const blogCategoryData = [
  { name: "Digital Marketing", slug: "digital-marketing" },
  { name: "Sustainable Living", slug: "sustainable-living" },
  { name: "Mental Health", slug: "mental-health" },
  { name: "Personal Finance", slug: "personal-finance" },
  { name: "Technology & AI", slug: "technology-ai" },
  { name: "Remote Work", slug: "remote-work" },
  { name: "Self-Care", slug: "self-care" },
  { name: "Content Creation", slug: "content-creation" },
  { name: "Productivity", slug: "productivity" },
  { name: "E-commerce", slug: "e-commerce" },
  { name: "Personal Branding", slug: "personal-branding" },
  { name: "Fitness & Wellness", slug: "fitness-wellness" },
  { name: "Travel & Adventure", slug: "travel-adventure" },
  { name: "Home & Design", slug: "home-design" },
  { name: "Social Media", slug: "social-media" },
  { name: "Relationships", slug: "relationships" },
  { name: "Gaming & Entertainment", slug: "gaming-entertainment" },
  { name: "Photography", slug: "photography" },
  { name: "Entrepreneurship", slug: "entrepreneurship" },
  { name: "Lifestyle", slug: "lifestyle" },
];

export const courseCategoryData = [
  { name: "Web Development", slug: "web-development" },
  { name: "Mobile Development", slug: "mobile-development" },
  { name: "Data Science", slug: "data-science" },
  { name: "Machine Learning", slug: "machine-learning" },
  { name: "Cloud Computing", slug: "cloud-computing" },
  { name: "DevOps & Infrastructure", slug: "devops-infrastructure" },
  { name: "UI/UX Design", slug: "ui-ux-design" },
  { name: "Graphic Design", slug: "graphic-design" },
  { name: "Digital Marketing", slug: "digital-marketing" },
  { name: "Business Management", slug: "business-management" },
  { name: "Project Management", slug: "project-management" },
  { name: "Leadership & Communication", slug: "leadership-communication" },
  { name: "Cybersecurity", slug: "cybersecurity" },
  { name: "Database Design", slug: "database-design" },
  { name: "Python Programming", slug: "python-programming" },
  { name: "JavaScript & React", slug: "javascript-react" },
  { name: "Financial Planning", slug: "financial-planning" },
  { name: "Artificial Intelligence", slug: "artificial-intelligence" },
  { name: "Blockchain & Crypto", slug: "blockchain-crypto" },
  { name: "SEO & Content Strategy", slug: "seo-content-strategy" },
];
