export const PERMISSIONS = Object.freeze({
  "branch:read": ["ADMIN", "BRANCH"],
  "branch:create": ["ADMIN"],
  "branch:update": ["ADMIN"],
  "staff:read": ["ADMIN", "BRANCH"],
  "staff:create": ["BRANCH"],
  "staff:update": ["BRANCH"],
  "staff:delete": ["BRANCH"],
  "customer:read": ["ADMIN", "BRANCH"],
  "customer:create": ["BRANCH"],
  "customer:update": ["BRANCH"],
  "customer:delete": ["BRANCH"],
  "lead:read": ["ADMIN", "BRANCH"],
  "lead:create": ["BRANCH"],
  "lead:update": ["BRANCH"],
  "lead:delete": ["BRANCH"],
  "policy:read": ["ADMIN", "BRANCH"],
  "policy:create": ["BRANCH"],
  "policy:update": ["BRANCH"],
  "policy:delete": ["BRANCH"],
  "renewal:read": ["ADMIN", "BRANCH"],
  "renewal:update": ["BRANCH"],
  "claim:read": ["ADMIN", "BRANCH"],
  "claim:create": ["BRANCH"],
  "claim:update": ["BRANCH"],
  "followup:read": ["ADMIN", "BRANCH"],
  "followup:create": ["BRANCH"],
  "followup:update": ["BRANCH"],
  "followup:delete": ["BRANCH"],
  "document:read": ["ADMIN", "BRANCH"],
  "document:create": ["BRANCH"],
  "document:delete": ["BRANCH"],
  "activity:read": ["ADMIN", "BRANCH"],
  "commission:read": ["ADMIN", "BRANCH"],
  "commission:create": ["BRANCH"],
  "commission:update": ["BRANCH"],
  "report:read": ["ADMIN", "BRANCH"],
  "dashboard:read": ["ADMIN", "BRANCH"],
});
