import express from 'express';
import cors from 'cors';
import morgan from 'morgan';
import authRoutes from './features/auth/auth.route.js';
import dashboardRoutes from './features/dashboard/dashboard.route.js';
import reportsRoutes from './features/reports/reports.route.js';
import branchesRoutes from './routes/branches.route.js';
import staffRoutes from './routes/staff.route.js';
import customersRoutes from './routes/customers.route.js';
import leadsRoutes from './routes/leads.route.js';
import policiesRoutes from './routes/policies.route.js';
import renewalsRoutes from './routes/renewals.route.js';
import claimsRoutes from './routes/claims.route.js';
import followUpsRoutes from './routes/follow-ups.route.js';
import documentsRoutes from './routes/documents.route.js';
import activitiesRoutes from './routes/activities.route.js';
import commissionsRoutes from './routes/commissions.route.js';
import { notFound } from './middlewares/not-found.middleware.js';
import { errorHandler } from './middlewares/error.middleware.js';

const app = express();
app.disable('x-powered-by');
app.use(cors({ origin: process.env.CORS_ORIGIN?.split(',') ?? true }));
app.use(express.json({ limit: '1mb' }));
app.use(express.urlencoded({ extended: false }));
app.use(morgan(process.env.NODE_ENV === 'production' ? 'combined' : 'dev'));
app.get('/health', (_req, res) => res.json({ success: true, data: { status: 'ok' } }));
app.use('/api/auth', authRoutes);
app.use('/api/dashboard', dashboardRoutes);
app.use('/api/reports', reportsRoutes);
app.use('/api/branches', branchesRoutes);
app.use('/api/staff', staffRoutes);
app.use('/api/customers', customersRoutes);
app.use('/api/leads', leadsRoutes);
app.use('/api/policies', policiesRoutes);
app.use('/api/renewals', renewalsRoutes);
app.use('/api/claims', claimsRoutes);
app.use('/api/follow-ups', followUpsRoutes);
app.use('/api/documents', documentsRoutes);
app.use('/api/activities', activitiesRoutes);
app.use('/api/commissions', commissionsRoutes);
app.use(notFound);
app.use(errorHandler);

export default app;
